# Generated by Django 5.2.8 on 2026-01-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_activity_awayperiod_meal_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
