# Generated by Django 5.2.8 on 2026-01-08 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0009_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='assigned_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
