# Generated by Django 5.2.8 on 2026-01-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0010_alter_meal_date_alter_roomassignment_assigned_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('social', 'Social Event'), ('educational', 'Educational'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('meeting', 'Meeting'), ('other', 'Other')], default='social', max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('requires_rsvp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe')], default='attending', max_length=20)),
                ('attended', models.BooleanField(default=False, help_text='Mark if student actually attended')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='hms.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to='hms.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
