# Generated by Django 5.2.8 on 2026-01-28 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_deferment_system_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.AddField(
            model_name='student',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Hostel 1', 'Hostel 1'), ('Hostel 2', 'Hostel 2'), ('Hostel 3', 'Hostel 3'), ('Hostel 4', 'Hostel 4'), ('Hostel 5', 'Hostel 5'), ('Hostel 6', 'Hostel 6'), ('Hostel 7', 'Hostel 7')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DefermentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferment_type', models.CharField(choices=[('fee_challenges', 'Fee Challenges'), ('motherhood_fatherhood', 'Motherhood/Fatherhood'), ('gainful_employment', 'Pursuing Gainful Employment'), ('family_disruption', 'Disruption of Family'), ('moving_country', 'Moving Out of the Country'), ('natural_calamity', 'Natural Calamity'), ('political_calamity', 'Political Calamity'), ('program_challenges', 'Challenges in the Current Program'), ('other', 'Others (Please State)')], help_text='Select the reason for deferment', max_length=30)),
                ('other_reason_detail', models.TextField(blank=True, help_text="If 'Others', please provide details")),
                ('start_date', models.DateField(help_text='Expected deferment start date')),
                ('end_date', models.DateField(help_text='Expected deferment end date')),
                ('reason', models.TextField(help_text='Detailed explanation of your deferment request')),
                ('contact_during_deferment', models.CharField(blank=True, help_text='Phone number during deferment', max_length=15)),
                ('supporting_documents', models.FileField(blank=True, help_text='Upload supporting documents if any', null=True, upload_to='deferment_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Application'), ('under_review', 'Sent for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resumed', 'Resumed Studies')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Administrative notes and feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hms.student')),
            ],
            options={
                'verbose_name': 'Deferment Request',
                'verbose_name_plural': 'Deferment Requests',
                'db_table': 'hms_leaverequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
