# Generated by Django 5.2.8 on 2026-01-30 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0015_student_hostel_defermentrequest_delete_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # migrations.RemoveField(
        #     model_name='event',
        #     name='created_by',
        # ),
        # migrations.RemoveField(
        #     model_name='eventrsvp',
        #     name='event',
        # ),
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together=None,
        ),
        # migrations.RemoveField(
        #     model_name='eventrsvp',
        #     name='student',
        # ),
        # migrations.RemoveField(
        #     model_name='loginactivity',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='message',
        #     name='recipient',
        # ),
        # migrations.RemoveField(
        #     model_name='message',
        #     name='sender',
        # ),
        # migrations.RemoveField(
        #     model_name='notification',
        #     name='user',
        # ),
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='student',
        # ),
        # migrations.RemoveField(
        #     model_name='roomchangerequest',
        #     name='current_room',
        # ),
        # migrations.RemoveField(
        #     model_name='roomchangerequest',
        #     name='requested_room',
        # ),
        # migrations.RemoveField(
        #     model_name='roomassignment',
        #     name='room',
        # ),
        # migrations.RemoveField(
        #     model_name='roomassignment',
        #     name='student',
        # ),
        # migrations.RemoveField(
        #     model_name='roomchangerequest',
        #     name='reviewed_by',
        # ),
        # migrations.RemoveField(
        #     model_name='roomchangerequest',
        #     name='student',
        # ),
        # migrations.RemoveField(
        #     model_name='visitor',
        #     name='created_by',
        # ),
        # migrations.RemoveField(
        #     model_name='visitor',
        #     name='student',
        # ),
        migrations.AlterModelOptions(
            name='defermentrequest',
            options={'ordering': ['-created_at']},
        ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='admin_notes',
        # ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='contact_during_deferment',
        # ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='other_reason_detail',
        # ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='reviewed_at',
        # ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='reviewed_by',
        # ),
        # migrations.RemoveField(
        #     model_name='defermentrequest',
        #     name='supporting_documents',
        # ),
        # migrations.RemoveField(
        #     model_name='maintenancerequest',
        #     name='photo',
        # ),
        # migrations.AddField(
        #     model_name='defermentrequest',
        #     name='admin_response',
        #     field=models.TextField(blank=True, help_text='Response from admin'),
        # ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        # migrations.AddField(
        #     model_name='maintenancerequest',
        #     name='admin_notes',
        #     field=models.TextField(blank=True, help_text='Notes from admin/warden'),
        # ),
        # migrations.AddField(
        #     model_name='maintenancerequest',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to='maintenance_images/'),
        # ),
        # migrations.AddField(
        #     model_name='maintenancerequest',
        #     name='location',
        #     field=models.CharField(default=django.utils.timezone.now, help_text='Specific location, e.g., Room 101, Common Room', max_length=100),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='maintenancerequest',
        #     name='resolved_at',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='deferment_type',
        #     field=models.CharField(choices=[('fee_challenges', 'Fee Challenges'), ('motherhood_fatherhood', 'Motherhood/Fatherhood'), ('special_exams', 'Special Exams'), ('sick_role', 'Sick Role (Medical)'), ('bereavement', 'Bereavement'), ('suspension_expulsion', 'Suspension/Expulsion'), ('natural_calamity', 'Natural Calamity')], help_text='Select the reason for deferment', max_length=30),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='end_date',
        #     field=models.DateField(),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='reason',
        #     field=models.TextField(help_text='Detailed explanation'),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='start_date',
        #     field=models.DateField(),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='status',
        #     field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        # ),
        # migrations.AlterField(
        #     model_name='defermentrequest',
        #     name='student',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferment_requests', to='hms.student'),
        # ),
        # migrations.AlterField(
        #     model_name='maintenancerequest',
        #     name='status',
        #     field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        # ),
        # migrations.AlterModelTable(
        #     name='defermentrequest',
        #     table=None,
        # ),
        # migrations.CreateModel(
        #     name='EmergencyAlert',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('location', models.CharField(blank=True, help_text='Location when alert was triggered', max_length=255)),
        #         ('is_resolved', models.BooleanField(default=False)),
        #         ('resolved_at', models.DateTimeField(blank=True, null=True)),
        #         ('admin_notes', models.TextField(blank=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='hms.student')),
        #     ],
        #     options={
        #         'ordering': ['-created_at'],
        #     },
        # ),
        # migrations.DeleteModel(
        #     name='AuditLog',
        # ),
        # migrations.DeleteModel(
        #     name='Event',
        # ),
        # migrations.DeleteModel(
        #     name='EventRSVP',
        # ),
        # migrations.DeleteModel(
        #     name='LoginActivity',
        # ),
        # migrations.DeleteModel(
        #     name='Message',
        # ),
        # migrations.DeleteModel(
        #     name='Notification',
        # ),
        # migrations.DeleteModel(
        #     name='Payment',
        # ),
        # migrations.DeleteModel(
        #     name='Room',
        # ),
        # migrations.DeleteModel(
        #     name='RoomAssignment',
        # ),
        # migrations.DeleteModel(
        #     name='RoomChangeRequest',
        # ),
        # migrations.DeleteModel(
        #     name='Visitor',
        # ),
    ]
