# Generated by Django 5.2.8 on 2026-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0019_room_message_attachment_loginactivity_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
