# Generated by Django 5.2.8 on 2026-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0020_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_type',
            field=models.CharField(choices=[('hostel', 'In Hostel'), ('off_campus', 'Off-Campus (Rent)')], default='hostel', max_length=20),
        ),
    ]
