# Generated by Django 5.2.8 on 2026-02-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0021_add_residence_type_and_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduating',
            field=models.BooleanField(default=False, help_text='Is the student in their graduating semester/year?'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_on_attachment',
            field=models.BooleanField(default=False, help_text='Is the student currently on industrial attachment?'),
        ),
    ]
