# Generated by Django 5.2.8 on 2026-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0022_student_is_graduating_student_is_on_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='category',
            field=models.CharField(choices=[('male_student', 'Male Student'), ('female_student', 'Female Student'), ('lgbtq', 'LGBTQ'), ('male_parent', 'Male Parents'), ('female_parent', 'Female Parents'), ('pwd', 'PWD')], default='male_student', max_length=20),
        ),
    ]
