# Generated by Django 5.2.8 on 2026-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0023_visitor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('none', 'None'), ('physical', 'Physical Disability'), ('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('mental', 'Mental Health Condition'), ('others', 'Others')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_details',
            field=models.TextField(blank=True, help_text="Specify details if 'Others' is selected", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program_of_study',
            field=models.CharField(blank=True, help_text='Department or Program of Study', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence_type',
            field=models.CharField(choices=[('hostel', 'In Hostel'), ('off_campus', 'Off-Campus (Rental)')], default='hostel', max_length=20),
        ),
    ]
