# Generated by Django 5.2.8 on 2026-02-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0024_student_disability_student_disability_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
