# Generated by Django 5.2.8 on 2026-02-09 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0026_lostitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEFERMENT', 'Deferment Manager'), ('MAINTENANCE_HOSTEL', 'Maintenance & Hostel Manager'), ('ACTIVITIES_ROOMS', 'Activities & Rooms Manager'), ('NEWS_ALERT', 'News & Announcements Manager'), ('VISITORS', 'Visitor Log Manager'), ('AUDIT_LOGS', 'Audit Compliance Officer')], max_length=20)),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='Role ID / National ID')),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
