# Generated by Django 5.2.8 on 2026-02-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0027_staffprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_month',
            new_name='price_per_semester',
        ),
    ]
