# Generated by Django 5.2.8 on 2026-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0029_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
