# Generated by Django 5.2.8 on 2026-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0030_alter_student_university_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='defermentrequest',
            name='contact_during_deferment',
            field=models.CharField(blank=True, help_text='Contact number during deferment', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='other_reason_detail',
            field=models.TextField(blank=True, help_text="Specific details for 'Others' reason", null=True),
        ),
        migrations.AddField(
            model_name='defermentrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Supporting documents (Medical reports, letters, etc.)', null=True, upload_to='deferment_docs/'),
        ),
        migrations.AlterField(
            model_name='defermentrequest',
            name='deferment_type',
            field=models.CharField(choices=[('fee_challenges', 'Fee Challenges'), ('motherhood_fatherhood', 'Motherhood/Fatherhood'), ('special_exams', 'Special Exams'), ('sick_role', 'Sick Role (Medical)'), ('bereavement', 'Bereavement'), ('suspension_expulsion', 'Suspension/Expulsion'), ('natural_calamity', 'Natural Calamity'), ('other', 'Others')], help_text='Select the reason for deferment', max_length=30),
        ),
    ]
