# Generated by Django 5.2.8 on 2026-03-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0031_defermentrequest_contact_during_deferment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(blank=True, help_text='Name of the hostel/hall', max_length=50, null=True),
        ),
    ]
