# Generated by Django 5.2.8 on 2026-03-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0033_adminsubscription_registrationpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='county',
        ),
    ]
