# Generated by Django 5.2.8 on 2026-03-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0034_remove_student_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meal', 'Meal & Kitchen'), ('finance', 'Finance & Payment'), ('maintenance', 'Maintenance & Support'), ('broadcast', 'General Broadcast'), ('system', 'System Alert')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Optional URL to redirect when clicked', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for system-wide broadcasts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
