# Generated by Django 5.2.8 on 2026-03-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0035_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g., Mathematics, Python, Accounting', max_length=100)),
                ('description', models.TextField(help_text='Details about what you can teach or need help with')),
                ('post_type', models.CharField(choices=[('offer', 'Offering Help (Tutor)'), ('request', 'Requesting Help (Student)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_posts', to='hms.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
