# Generated by Django 5.2.8 on 2026-03-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0039_alter_staffprofile_role_staffregistrationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_health_management', models.BooleanField(default=False, verbose_name='Health Management')),
                ('can_accommodation', models.BooleanField(default=False, verbose_name='Accommodation & Deferment')),
                ('can_dining', models.BooleanField(default=False, verbose_name='Dining Management')),
                ('can_maintenance', models.BooleanField(default=False, verbose_name='Maintenance Requests')),
                ('can_visitors', models.BooleanField(default=False, verbose_name='Visitors Log')),
                ('can_news', models.BooleanField(default=False, verbose_name='News Alerts')),
                ('can_payments', models.BooleanField(default=False, verbose_name='Payments & M-Pesa')),
                ('can_audit', models.BooleanField(default=False, verbose_name='Audit Logs')),
                ('can_emergency', models.BooleanField(default=False, verbose_name='Emergency Alerts')),
                ('can_chat', models.BooleanField(default=False, verbose_name='Student Chat')),
                ('can_admin', models.BooleanField(default=False, verbose_name='System Administration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='hms.staffprofile')),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'verbose_name_plural': 'Staff Permissions',
            },
        ),
    ]
