# Generated by Django 5.2.8 on 2026-05-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0041_alter_staffprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HEALTH_MGR', 'Health Manager'), ('MAINT_SUP', 'Maintenance Supervisor'), ('WARDEN', 'Warden'), ('FINANCE', 'Finance Officer'), ('SECURITY', 'Security Officer'), ('NEWS_EDITOR', 'News Editor'), ('AUDITOR', 'Auditor'), ('EMERGENCY', 'Emergency Coordinator'), ('SUPPORT', 'Support Agent'), ('DIPLOMA', 'Diploma Coordinator'), ('DEAN_HHS', 'Dean of Students'), ('DEFERMENT', 'Deferment Officer'), ('DEPT_MCS', 'Dept MCS Coordinator'), ('DVC_ASA', 'DVC ASA'), ('VC', 'Vice Chancellor'), ('DVC', 'Deputy Vice Chancellor'), ('REG_ADMIN', 'Register Admin'), ('REG_USER', 'Register User'), ('DEAN_GRAD', 'Dean - Graduate School'), ('DIR_RESOURCE', 'Director - Resource Mobilization'), ('DIR_TVET', 'Director - TVET'), ('NEWS_AUDITOR', 'News Auditor')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('whatsapp_notifications', models.BooleanField(default=False, help_text='Receive WhatsApp notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
