# Generated by Django 5.2.8 on 2026-06-10 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0048_adminsubscription_billing_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisHelpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_24hr', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_24hr', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentalHealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Description or main content of the resource')),
                ('resource_type', models.CharField(choices=[('article', 'Article/Guide'), ('audio', 'Audio/Meditation'), ('video', 'Video Resource'), ('contact', 'Contact/Support Group')], default='article', max_length=20)),
                ('external_link', models.URLField(blank=True, help_text='Link to external website or video', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('vice_chancellor', 'Vice Chancellor'), ('deputy_vice_chancellor', 'Deputy Vice Chancellor'), ('register_admin', 'Register Admin'), ('register_user', 'Register User'), ('dean_of_students', 'Dean of Students'), ('dean_graduate_school', 'Dean - Graduate School'), ('director_resource', 'Director - Resource Mobilization'), ('director_tvet', 'Director - TVET'), ('deferment_officer', 'Deferment Officer'), ('dept_mcs', 'Dept MCS Coordinator'), ('health_manager', 'Health Manager'), ('maintenance_sup', 'Maintenance Supervisor'), ('warden', 'Warden'), ('finance_officer', 'Finance Officer'), ('security_officer', 'Security Officer'), ('news_editor', 'News Editor'), ('news_auditor', 'News Auditor'), ('emergency_coord', 'Emergency Coordinator'), ('support_agent', 'Support Agent'), ('auditor', 'Auditor'), ('diploma_coordinator', 'Diploma Coordinator'), ('dept_coordinator', 'Department Coordinator'), ('librarian', 'Head Of Library Services (HOLS)'), ('counsellor', 'Counsellor')], max_length=50),
        ),
        migrations.CreateModel(
            name='CounsellingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, the request will not be linked to the student profile visible to the counsellor.')),
                ('reason', models.TextField(help_text='Briefly describe what you are going through')),
                ('urgency', models.CharField(choices=[('low', 'Low (General Advice/Support)'), ('medium', 'Medium (Struggling, Need to talk soon)'), ('high', 'High (Crisis, Need immediate help)')], default='medium', max_length=10)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('counsellor_notes', models.TextField(blank=True, help_text='Private notes for the counsellor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counselling_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counselling_requests', to='hms.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
