# Generated by Django 5.2.8 on 2026-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0050_studentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_school',
            field=models.CharField(blank=True, choices=[('library', 'Library'), ('sasa', 'SASA – School of Arts and Social Sciences'), ('sed', 'SED – School of Education'), ('sob', 'SOB – School of Business'), ('shhs', 'SHHS – School of Health and Human Sciences'), ('sees', 'SEES – School of Environmental and Earth Sciences'), ('shss', 'SHSS – School of Humanities and Social Sciences'), ('spas', 'SPAS – School of Performing Arts and Sports'), ('finance', 'Finance'), ('dean', 'Dean of School')], help_text='Academic School', max_length=50, null=True),
        ),
    ]
